import type { VercelRequest, VercelResponse } from "@vercel/node";
const companies: Record<string, object> = {
  "co_001":{"id":"co_001","name":"NovaPay","industry":"Fintech","stage":"series_b","revenue":8400000,"valuation":62000000,"growthRate":48.2,"employees":94,"location":"San Francisco, CA","status":"active","dataVerified":true,"ndaSigned":true,"logo":"","description":"B2B payments infrastructure platform serving mid-market businesses.","founded":2020,"arr":8200000,"grossMargin":78,"burnRate":620000,"runwayMonths":18,"keyMetrics":[{"label":"MRR","value":"$683K","change":4.2},{"label":"NRR","value":"118%","change":3.1},{"label":"Churn","value":"1.8%","change":-0.3},{"label":"CAC Payback","value":"14mo","change":-2}]},
  "co_002":{"id":"co_002","name":"CloudOps Pro","industry":"SaaS / Infrastructure","stage":"series_a","revenue":3200000,"valuation":28000000,"growthRate":72.1,"employees":41,"location":"Austin, TX","status":"active","dataVerified":true,"ndaSigned":true,"logo":"","description":"Cloud cost optimization and infrastructure management platform.","founded":2021,"arr":3100000,"grossMargin":82,"burnRate":380000,"runwayMonths":22,"keyMetrics":[{"label":"MRR","value":"$258K","change":6.1},{"label":"NRR","value":"124%","change":4.2},{"label":"Churn","value":"1.2%","change":-0.4},{"label":"CAC Payback","value":"11mo","change":-3}]},
  "co_003":{"id":"co_003","name":"HealthVault","industry":"HealthTech","stage":"series_a","revenue":5100000,"valuation":38000000,"growthRate":31.4,"employees":68,"location":"Boston, MA","status":"monitoring","dataVerified":false,"ndaSigned":true,"logo":"","description":"Patient data management and clinical analytics platform.","founded":2019,"arr":4900000,"grossMargin":71,"burnRate":520000,"runwayMonths":12,"keyMetrics":[{"label":"MRR","value":"$408K","change":2.6},{"label":"NRR","value":"104%","change":-1.1},{"label":"Churn","value":"3.2%","change":0.4},{"label":"CAC Payback","value":"22mo","change":2}]},
  "co_004":{"id":"co_004","name":"DataStream AI","industry":"AI / ML","stage":"series_b","revenue":12800000,"valuation":95000000,"growthRate":88.6,"employees":127,"location":"New York, NY","status":"active","dataVerified":true,"ndaSigned":true,"logo":"","description":"AI-powered data pipeline and analytics platform for enterprises.","founded":2020,"arr":12400000,"grossMargin":76,"burnRate":1100000,"runwayMonths":20,"keyMetrics":[{"label":"MRR","value":"$1.03M","change":7.4},{"label":"NRR","value":"128%","change":5.8},{"label":"Churn","value":"0.9%","change":-0.2},{"label":"CAC Payback","value":"10mo","change":-4}]},
  "co_005":{"id":"co_005","name":"RetailEdge","industry":"Retail Tech","stage":"growth","revenue":22500000,"valuation":145000000,"growthRate":19.3,"employees":204,"location":"Chicago, IL","status":"active","dataVerified":true,"ndaSigned":true,"logo":"","description":"Omnichannel retail operations and inventory optimization platform.","founded":2017,"arr":21800000,"grossMargin":69,"burnRate":800000,"runwayMonths":28,"keyMetrics":[{"label":"MRR","value":"$1.82M","change":1.6},{"label":"NRR","value":"108%","change":0.4},{"label":"Churn","value":"2.1%","change":0.1},{"label":"CAC Payback","value":"18mo","change":1}]},
  "co_006":{"id":"co_006","name":"LogiChain","industry":"Supply Chain","stage":"series_a","revenue":2900000,"valuation":21000000,"growthRate":42.7,"employees":35,"location":"Seattle, WA","status":"watchlist","dataVerified":false,"ndaSigned":false,"logo":"","description":"AI-driven supply chain visibility and demand forecasting platform.","founded":2021,"arr":2800000,"grossMargin":74,"burnRate":310000,"runwayMonths":16,"keyMetrics":[{"label":"MRR","value":"$233K","change":3.6},{"label":"NRR","value":"112%","change":2.1},{"label":"Churn","value":"2.4%","change":0.2},{"label":"CAC Payback","value":"16mo","change":-1}]},
  "co_007":{"id":"co_007","name":"EduCore","industry":"EdTech","stage":"seed","revenue":820000,"valuation":9500000,"growthRate":95.2,"employees":18,"location":"Denver, CO","status":"active","dataVerified":false,"ndaSigned":true,"logo":"","description":"Adaptive learning management system for K-12 and higher education.","founded":2022,"arr":800000,"grossMargin":84,"burnRate":140000,"runwayMonths":14,"keyMetrics":[{"label":"MRR","value":"$66K","change":7.9},{"label":"NRR","value":"122%","change":6.2},{"label":"Churn","value":"1.1%","change":-0.5},{"label":"CAC Payback","value":"9mo","change":-2}]},
  "co_008":{"id":"co_008","name":"SecureVault","industry":"Cybersecurity","stage":"series_c","revenue":38000000,"valuation":290000000,"growthRate":26.8,"employees":312,"location":"Washington, DC","status":"active","dataVerified":true,"ndaSigned":true,"logo":"","description":"Enterprise security data platform and threat intelligence solution.","founded":2016,"arr":37100000,"grossMargin":80,"burnRate":1800000,"runwayMonths":32,"keyMetrics":[{"label":"MRR","value":"$3.09M","change":2.2},{"label":"NRR","value":"113%","change":1.4},{"label":"Churn","value":"1.5%","change":-0.1},{"label":"CAC Payback","value":"16mo","change":-2}]}
};
export default function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  const id = req.query.id as string;
  const company = companies[id] ?? Object.values(companies)[0];
  res.json(company);
}
